# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name=b'Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'Modificado em')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name=b'Identificador')),
                ('description', models.TextField(blank=True, verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'Pre\xc3\xa7o')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'Modificado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Category', verbose_name=b'Categoria')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
