# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-10 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180827_2105'),
        ('catalogo', '0002_auto_20180902_1807'),
    ]

    operations = [
    ]
